// /// <reference path="../node_modules/@types/angular/index.d.ts" />
// /// <reference path="../node_modules/@types/angular-route/index.d.ts" />
// /// <reference path="../node_modules/@types/angular-material/index.d.ts" />
/// <reference path="Modules.ts" />
/// <reference path="Routes.ts" />
/// <reference path="Startup.ts" />
/// <reference path="models/TodoList.ts" />
/// <reference path="models/TodoItem.ts" />
/// <reference path="contracts/IRootScope.ts" />